### PR TITLE
plugin/FlashHelper: New plugin for firmware-assisted flashing

### PR DESCRIPTION
**Pull request by algernon**
This introduces a new plugin - `FlashHelper` - to aid with firmware-assisted flashing. During the flashing process, this plugin can temporarily disable the `Prog` key.

Addresses the firmware part of keyboardio/Chrysalis#509.

### CODE REVIEW

**Comment by obra** [comment]
I think I'd rather expose the flashing lockout key through an API on the hardware, so there's no setup required (or possible) other than including the plugin.

**Comment by algernon** [comment]
I've also considered that option, but figured I'd make the plugin a bit more generic instead of adding a prop to the hardware. But not requiring setup is a valid point, I'll redo this in a bit.

**Comment by algernon** [comment]
Hm, there's a problem with this approach: what if the device supports multiple prog keys? For example, the Dygma Raise has one on each hand. I suppose we'll need a list instead of a single value. I'll finish up the moving to Props first, and will then push another step with turning the address into a list.

**Comment by algernon** [comment]
Aight, we now support multiple prog keys!

Though, still only one set for the Raise, because I can't remember which one's the other one, and official documentation mentions R0C0 only. We can easily add another when I verify it later.

**Pull request merged**
