### PR TITLE
Remove kaleidoscope/plugin/LEDControl/BootAnimation.*

### PR DESCRIPTION
**Pull request by algernon**
Removes said files, and also cleans up the `LED_A`, `LED_Q`, etc defines from `hardware::Model01`.

### CODE REVIEW

**Comment by obra** [comment]
We have another way to do this now, right?

**Comment by obra** [comment]
Huh. I thought we had new code to light up a key that scanned the keymap to
find it.

> ᐧ

**Comment by algernon** [comment]
We don't, but it's easy to write such a plugin. One that doesn't even lock up the keyboard while it does its thing ;)

(And neither `bootAnimation` nor the removed LED_ defines are needed for that)

Should I write that prior to dropping `bootAnimation`?

**Comment by algernon** [comment]
Just pushed a new commit that adds the new `LEDEffect-BootAnimation` plugin, which does pretty much the same as `bootAnimation()`, but better.

**Pull request merged**
