### PR TITLE
Merge KeyboardioHID as (part of) a driver

### PR DESCRIPTION
**Pull request by algernon**
In an effort to move towards a single repository and library we use, merge KeyboardioHID as driver/hid/keyboardio/HID.

For a cleaner, saner history, KeyboardioHID's history has not been kept, the files were copied as of keyboardio/KeyboardioHID@dccbd8782ebc2c035a200c97abca9f0f3782d96f.

Apart from changing the included paths, making cpplint happy, and running astyle, no other changes were made.

### CODE REVIEW

**Comment by algernon** [comment]
This compiles clean, to the same size as with master, even with the separate KeyboardioHID library removed, so it appears there aren't any lurking references either.

The reason I'm keeping it as draft for now, is naming and structure. Right now, everything is copied under `src/kaleidoscope/driver/hid/keyboardio/HID/`, and... that doesn't really look or feel good. Ideally, we'd have it all under `src/kaleidoscope/driver/hid/keyboardio/`, perhaps with a better structure. But this is a fairly small thing, cosmetics, we could argue, so I'm ok with postponing the cleanup, if getting this merged is deemed more important.

**Comment by obra** [comment]
I don't want to leave this hanging around as a draft for a long time, as that gets in the way of changes being made to it.

I don't have a need to keep the name 'KeyboardioHID' anywhere.   I feel like getting the name 'USB' in there would make sense. If we were going to integrate tightly into Kaleidoscope while preserving the ability to have a second HID implementation (say for Bluetooth), is there code we can get rid of?

**Comment by gedankenexperimenter** [comment]
The duplicate `HIDTables.h` file should get removed, so it only exists in one place.

**Comment by algernon** [comment]
Hmm... I _think_ `kaleidoscope::driver::hid::keyboardio::usb::` makes sense, so I'll go ahead and do that.

**Comment by algernon** [comment]
- Moved KeyboardioHID to `src/kaleidoscope/driver/hid/keyboardio/usb/`
- Changed the main header from `HID/KeyboardioHID.h` to `usb/USBHID.h`
- Removed the HID.o filename conflict, by renaming the file in KeyboardioHID to `HID_.*`
- Adjusted the include paths to be relative includes from `src/`, rather than the current dir, for clarity.
- Removed the `HIDTables.h` copy

**Comment by obra** [comment]
It looks like the simulator hadn't been updated for these changes and was bombing out. I've just pushed a first-pass at cleaning this up.

**Comment by obra** [comment]
Actually, I'm seeing a regression:

```
make[2]: Entering directory '/kaleidoscope/tests/plugins/TopsyTurvy/basic'
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from GeneratedKTest
[ RUN      ] GeneratedKTest.0_KtestSourceFilename
[ INFO     ] test: /kaleidoscope/tests/plugins/TopsyTurvy/basic/test.ktest
[       OK ] GeneratedKTest.0_KtestSourceFilename (0 ms)
[ RUN      ] GeneratedKTest.1_TopsyTurvyWithoutShift
[       OK ] GeneratedKTest.1_TopsyTurvyWithoutShift (0 ms)
[ RUN      ] GeneratedKTest.2_TopsyTurvyWithShift
/kaleidoscope/testing/VirtualDeviceTest.cpp:140: Failure
Value of: observed_keycodes
Expected: is empty
  Actual: { '\x1E' (30), '\xE1' (225) }, which has 2 elements
Report should be empty (i=3)
[  FAILED  ] GeneratedKTest.2_TopsyTurvyWithShift (0 ms)
[----------] 3 tests from GeneratedKTest (0 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GeneratedKTest.2_TopsyTurvyWithShift

 1 FAILED TEST
make[2]: *** [/kaleidoscope/testing/makefiles/testcase.mk:49: run] Error 1
make[2]: Leaving directory '/kaleidoscope/tests/plugins/TopsyTurvy/basic'
```

**Comment by gedankenexperimenter** [comment]
I'm planning to take this and run with it, leading up to some major HID API changes.

**Comment by gedankenexperimenter** [comment]
I am attempting to bring this PR up to date.  I first copied it in its previous form to a [new branch](https://github.com/keyboardio/Kaleidoscope/tree/f/driver/keyboardiohid-orig) so that we can easily restore it if necessary.

**Comment by gedankenexperimenter** [comment]
This PR would close #1117.

**Comment by algernon** [comment]
Looks good on first read. The commit could use a cleanup, but other than that, the rest looks great.

**Comment by gedankenexperimenter** [comment]
> Looks good on first read. The commit could use a cleanup, but other than that, the rest looks great.

I plan to clean this up after #1143 gets merged, since it looks like that one is about ready to go.

**Comment by gedankenexperimenter** [comment]
The commit history of this one is now fairly sensible, starting with simply copying the current KeyboardioHID source files into Kaleidoscope, then showing all the logical changes from there.

**Comment by gedankenexperimenter** [comment]
Rebased, and looking fully-functional now.

**Comment by gedankenexperimenter** [comment]
I'm back to the old question of where to put the documentation regarding this change.  It's a pretty significant one, but there's no place that's obviously the right spot to put it in either NEWS.md or UPGRADING.md.  I feel like it should get a mention in at least one of those, but it shouldn't require any particular action on the part of a user, and it's entirely backwards compatible.

**Comment by obra** [comment]
I feel like NEWS might want to have a "new features" section?

**Comment by gedankenexperimenter** [comment]
> I feel like NEWS might want to have a "new features" section?

It does, but this doesn't seem like a new feature to me.  I guess there's precedent for this kind of thing going in that section, though.  One of the entries there is "Transition to a monorepo", which was similar in that code was reorganized without affecting the feature set at all.  I'll add an entry there.

**Comment by gedankenexperimenter** [comment]
I have updated this to include recent changes to KeyboardioHID.  Is it finally time to consider merging this so we can stop dealing with repositories getting out of sync?

**Comment by obra** [comment]
Based on some discussions over the past few days, it's increasingly looking like we might have to jump to TinyUSB for the Model 100 and newer. I'm not quite sure what this means for this PR yet.

**Comment by obra** [comment]
KeyboardioHID has moved into the Kaleidoscope repo, but as a standalone library for the moment.

@tlyu is working on an alternate refactoring that's going to lift parts of KeyboardioHID into Kaleidoscope to make it easier to reuse things like our HID descriptors with TinyUSB and Bluetooth.

**Pull request closed without merging**
