### PR TITLE
Merge a number of things into the Kaleidoscope object

### PR DESCRIPTION
**Pull request by algernon**
This does a number of things, some of them trivial stuff, some not. I opted to open one PR that does three things in three commits, rather than three PRs that almost depend on each other. If you don't like some of these changes, let me know, and I'll pull the commit from the PR.

The gist is this, though:

- `plugin.h` was merged into `Kaleidoscope.h`, because having a header for a single class definition is pointless. There used to be a reason for this, when `Layer` was a `KeyboardioPlugin` too: we had to avoid circular header dependencies. This is no longer the case, however, and `plugin.h` can be safely merged to `Kaleidoscope.h.`.
- `keyswitch_state.h` was merged into `key_events.h`, because keyswitch state is pretty much only used by the key event handling code, and similarly to `plugin.h`, the need to have it separated exists no more.
- Hooks were moved into the `Kaleidoscope` object, because they are integral part of the framework anyway. This made it possible to remove some workarounds, like the `event_handler_hook_use(NULL)` call in `Kaleidoscope.setup`, or the `memset` in its constructor.

The first two commits are just rearrangements, and has no real effect. The third, the hook one, decreases code size by about 56 bytes. I kept around some `#define`s, so that plugins don't need to be updated immediately. Those can be removed later, if need be.

I think the first two commits are straightforward, but the third one's a bit larger, and more involved.

I also planned to merge `key_events` into `Kaleidoscope`, for similar reasons as the hooks, but didn't get there yet. Lets see how you like these changes, before I do another round =)

### CODE REVIEW

**Comment by obra** [comment]
The only bit of this that isn't +1000 is merging the keyswitch state stuff with the key event stuff.
We already don't do a great job of not conflating switch events with key events.

**Comment by algernon** [comment]
Updated, pulled the keyswitch merging!

**Comment by algernon** [comment]
Ok, not quite ready yet. The linker optimizes `handle_key_event` out now.

**Comment by algernon** [comment]
Should be fixed now.

**Pull request merged**
