### PR TITLE
Initial work on programmatic testing infrastructure based on googletest

### PR DESCRIPTION
**Pull request by paniag**
Definitely needs some TLC, but this framework has already reproduced #840 and verified its fix.  My hope is that this framework can be extended by myself and others in the future to provide the basis for constructing a regression test suite and to validate expected behavior (at a minimum).

Current state along with suggestions for future direction can be found in testing/TODO.txt.  In particular, this file contains notes on what is needed before this PR should be merged.

Note: this PR is against keyboardio/Kaleidoscope:master by default, but could certainly merge with testing or stay on its own branch.

Questions, comments, and concerns are all welcome.

### CODE REVIEW

**Comment by algernon** [comment]
I'll be pushing to [algernon/898-updates](https://github.com/keyboardio/Kaleidoscope/tree/algernon/898-updates). Already merged master into that, and pushed a small update to the Dockerfile (master's version of it), to install cmake as well.

**Comment by obra** [comment]
@algernon what does the attempted build look like with verbose building turned on?

**Comment by algernon** [comment]
For the record: the issue was that my bundle wasn't on the right branch. It compiles fine now.

**Comment by algernon** [comment]
This was superceded by #908, which has been merged. \o/

**Comment by obra** [comment]
(Didn't this PR have some additional tests based on the simulator, which aren't yet merged? -- even if it's not ready to do, I don't want to lose that work.)

**Comment by algernon** [comment]
Good point. Reopening!

**Pull request closed without merging**
