### PR TITLE
Added Arduino IDE install instructions

### PR DESCRIPTION
**Pull request by Jennigma**
Completed a first draft of the IDE install instructions through flashing the board with the unedited sketch. 

Also made a couple edits as suggested by @algernon, and a few other refinements I noticed.

### CODE REVIEW

**Comment by obra** [comment]
Yay! Thank you.

Just as a note, It's not a huge deal, but I'd thought you were going to be pushing docs into the 'wiki' repo, rather than the main repo.  (Also, generally, for stuff in the code repo, the informal policy has been for someone other than the submitter to merge a pull request (or for someone to +1 the submitter merging it.)
I don't know that we need that level of cross-check for docs, but I'd rather we decide that explicitly.

**Comment by algernon** [comment]
I'd suggest reviews for docs too - it's easier to give useful feedback for PRs than for already merged things.

**Comment by Jennigma** [comment]
I'm sorry, I wasn't at all sure where you wanted me to put things, or how to properly submit them.

I have no experience contributing to git repos-- zero skills. Please learn me up. :-) I've only ever cloned and built things in the past. I've been whining at my coder buddies for days now as I've been stumbling through git tutorials in idle moments and increasing my confusion. Wheee, climbing all the learning curves at once!

I wanted to get things out into the world and figured I wasn't really going to screw up anything irretrievably, so I went ahead and started publishing. 

I am more than happy to follow any guidelines and processes you explain to me, and to edit & rearrange what I've submitted in any way you think would be useful. Just let me know. :-)

**Comment by obra** [comment]
No apologies necessary! (And the work on doc is -hugely- appreciated.  Indeed, nothing bad happened. I suspect @algernon and I should make some decisions and write things down for contribution guidelines. 

The fact that you got a branch into a Pull Request on what may have been your first try is damn good. 

If you’d done exactly that, but not merged that into master (which you may have done from the GUI or by clicking on the pull request on the website), it would have been basically perfect.

**Comment by Jennigma** [comment]
> If you’d done exactly that, but not merged that into master (which you may have done from the GUI or by clicking on the pull request on the website), it would have been basically perfect.

I merged it deliberately. Wasn't sure how I was supposed to operate. Created the initial doc Thursday, and then merged in my Friday changes last night.

If you sketch out processes for common git tasks in the way you did for the Arduino IDE I can turn the notes into readable instructions.

/rant 

More than that, I will turn them into the seed of a task-based intro to git and try to publicize it enough that folks like me can find it. Every tutorial out there starts with the git equivalent of "Hello World" and wants me to swallow the whole damned ocean before they teach me to swim. 

Very, very few folks these days end up as beginners on git because they are competent programmers looking for a code repository. They end up on git because they heard of some nifty thing and they want a copy, but the website about it that their friend pointed out says they have to get the code and build it. And I'm fairly confident in saying there is no guide out there for this use case, because I looked. A lot. And I can JFGI with the best of them. It's tragic. 

I get it that git's really complicated, but it's not THAT hard or no one would use it willingly, and it certainly wouldn't have won the Internet SCM beauty contest. It is possible to create a practical reference to it. An empty repository is NOT the common case for beginners.

I think I counted six commands for "there's code over there, and I want to copy it over here," and can't find a single reference that says, "Use clone when you're creating an initial copy of an existing repo. Use pull to update that copy if the existing repo changes, and you want to update your local copy with your changes. Use... " I forget the rest offhand. But I'm sure you take my point. 

/rant off

:-)

**Pull request merged**
