### PR TITLE
Add a Rust version of focus-send

### PR DESCRIPTION
**Pull request by algernon**
This adds `bin/focus-send.rs`, a Rust re-implementation of the `focus-send` script. The goal is to eventually have a static binary we can ship with Arduino tooling, that works across all supported platforms (and more), unlike the shell script, which does not work natively on Windows.

The Rust version should be functionally the same as the current `bin/focus-send` script, and compatible, too: same CLI interface, respects the `DEVICE` environment variable, and so on. It does have a `--device` command line option (and `--version` and `--help`), but other than that, works the same as the shell script.

I chose not to import the full git history of the tool, as it would add little value.

### CODE REVIEW

**Comment by obra** [comment]
I don' think the source for this should live in bin/ 

maybe a tools/ directory?

**Comment by algernon** [comment]
Moved it to tools/. Also added the minimum Rust version needed to its `Cargo.toml`.

**Comment by tlyu** [comment]
Thanks for working on this!

Porting to Rust means that people who want to work on Kaleidoscope itself have an additional requirement to install a Rust toolchain. This might raise new barriers to entry. It might be a good idea to seek some broader feedback on this possible impact?

Using Rust strings means a behavior change when the keyboard sends invalid UTF-8. With the shell-based version, those invalid characters would be passed through for the terminal emulator window to deal with, instead of possibly causing an error in Rust. This is possibly minor, because as far as I know, Focus plugins (almost?) all stick to purely ASCII output.

Minor: Default device name on macOS for my Model 01 is `/dev/cu.usbmodemCkbio01E1` (needs a `1` appended; not sure if this varies across macOS releases). While possibly out of scope for this port, it might be nice to update it. There's an open issue (#547) for this.

**Comment by algernon** [comment]
> Porting to Rust means that people who want to work on Kaleidoscope itself have an additional requirement to install a Rust toolchain. This might raise new barriers to entry. It might be a good idea to seek some broader feedback on this possible impact?

Indeed, it might, but the shell script isn't going anywhere anytime soon, it will still be there for convenience's sake. The main aim of the Rust port is to let us use it from Arduino tooling: pre-built binaries could be shipped for the three major platforms.

> Using Rust strings means a behavior change when the keyboard sends invalid UTF-8. With the shell-based version, those invalid characters would be passed through for the terminal emulator window to deal with, instead of possibly causing an error in Rust. This is possibly minor, because as far as I know, Focus plugins (almost?) all stick to purely ASCII output.

Yep, invalid UTF-8 will cause issues. While the Rust port is reasonably lax in what it reads from the keyboard (invalid UTF-8 will not break it, it will just get turned into `?` or something similar), the commands sent do need to be valid UTF-8. There are very few Focus plugins that deal with text, most are serialized numbers and the like. The major exception is likely the `LayerNames` plugin which does handle text, but in all fairness, that should also only deal with valid UTF-8. The firmware does little validation due to resource constrains, though.

I do not think this should be a problem. In fact, I'd rather think of it as a feature.

> Minor: Default device name on macOS for my Model 01 is `/dev/cu.usbmodemCkbio01E1` (needs a `1` appended; not sure if this varies across macOS releases). While possibly out of scope for this port, it might be nice to update it. There's an open issue (#547) for this.

We should probably switch to using the Model100's device name as a default at this point. On top of all everything, the Rust port could reasonably easily scan available USB devices, and choose the first supported USB serial device as a default. That's much harder to do in the shell script (portably), but almost trivial in Rust. But I'd do that as a followup.

**Comment by obra** [comment]
We should switch to probing for the device port. arduino-cli gives us the rope and it’s not safe to assume any one specific keyboard.

**Comment by algernon** [comment]
Pushed a new commit that tries to detect the *first* Keyboardio keyboard and use that, unless there's a device explicitly specified. The detection works on all 3 platforms.

However, I just tried to test the tool on Windows 10, and it gets stuck on reading, so I will have to rummage around a bit there to see what's up.

**Comment by algernon** [comment]
Found a workaround for the Windows problem. I've personally tested the tool on both Linux and Windows 10. Windows 10 is a bit iffy (as in, it's slow), but it works fine otherwise. I have not tested it on macOS myself, yet.

**Comment by algernon** [comment]
Finally got around to test this on macOS too. Compiles & works fine there, too. I do want to set up automatic builds for all three platforms via GitHub Actions, but that's - at the moment - is rather low priority. Would be nice if the rest could go in meanwhile. O:)

I've been using the tool daily for a while now, started to even before I opened the PR, and on Linux it's been working well. Having device autodetection and the `--device` option is very convenient.

**Comment by tlyu** [comment]
Thanks for working on this! Tested successfully on an Intel MBP running macOS 10.15.7 and a Model 01.

A verbose mode that also lists the autodetected and used devices might be good.

The autodetection code is a bit deeply nested for my liking, but this is a somewhat short program, so maybe it's OK for now.

**Comment by algernon** [comment]
Closing this, as we ended up deciding to use a [separate repository](https://github.com/keyboardio/focus-send) to make it easier to auto-build and publish binaries. It's functionally the same as this PR, but with the full history, rather than a trimmed one.

I'll do the binary build magic tomorrow. Feel free to open feature requests there, I'll eventually get there to handle them, too!

**Pull request closed without merging**
