### PR TITLE
Simplify our docker execution

### PR DESCRIPTION
**Pull request by obra**
We no longer need to copy over a separate arduino bundle for docker

### CODE REVIEW

**Comment by gedankenexperimenter** [comment]
So far, no good.  For me, it hangs on:
```
Building the docker image...
```

**Comment by obra** [comment]
That could be a docker network issue.  In the root of Kaleidoscope,
"docker build -t kaleidoscope/docker etc" will perform the same action but
verbosely.

**Comment by gedankenexperimenter** [comment]
I guess the first time running it takes much longer, but subsequent runs are faster.  Thanks.  I'll test it out some more.

**Comment by gedankenexperimenter** [comment]
Now I can get this amusing error:
```
Using Kaleidoscope from /kaleidoscope
/usr/bin//ar: /kaleidoscope-persist/temp/build/3456739503-1061.ino/1061.ino.a: malformed archive
Multiple libraries were found for "Kaleidoscope.h"
  Used: /kaleidoscope
  Not used: /kaleidoscope
```
I check out this PR, then:
1. `rm -rf .arduino`
2. `docker image rm kaleidoscope/docker`
3. `make setup`
4. `make docker-simulator-tests`
[everything good so far]
5. check out my `mousekeys-wip` branch, with all the changes from this PR
6. `make docker-simulator-tests`
[this is where I get that error]

Prior to the Kaleidoscope symlink changes, I could get things to work by making sure the two versions were identical.  With the symlinks, I haven't gotten that sketch to build successfully yet, unfortunately.

**Comment by obra** [comment]
If you change branches, you need to `make clean` Otherwise arduino will
cache the old build pretty aggressively and the symbols won't line up :/

**Comment by gedankenexperimenter** [comment]
With the new changes, after switching branches, `make docker-clean` was insufficient, but `docker volume rm kaleidoscope-persist` did the trick after that failed.

**Comment by obra** [comment]
Did you have any luck grabbing a listing of what was left in kaleidoscope-persist after the make docker-clean?

**Comment by gedankenexperimenter** [comment]
> Did you have any luck grabbing a listing of what was left in kaleidoscope-persist after the make docker-clean?

Sorry; I forgot to capture that; I should be able to reproduce it shortly.

**Comment by gedankenexperimenter** [comment]
Here's a [gist with the list of files from `/kaleidoscope-persist` and `/kaleidoscope`](https://gist.github.com/3c927674e80b0aa29a0a920944786934).

**Comment by gedankenexperimenter** [comment]
With the most recent change, I can now confirm that switching branches, then `make docker-clean`, followed by running that testcase works properly, with no errors.

**Pull request merged**
