### PR TITLE
Preparations for #695

### PR DESCRIPTION
**Pull request by algernon**
These are some preparations to make #695 simpler, by doing many invasive changes _before_ the new APIs get introduced:

- Move hardware plugins to the `kaleidoscope::device` namespace.
- Include `key_indexes.h` from `Kaleidoscope.h`, and remove the includes from the device plugins.
- Deprecate named hardware object aliases (eg, the global `ErgoDox`, `KBD4x`, etc symbols)
- Redesign how hardware classes and objects are defined: from `HARDWARE_IMPLEMENTATION` and `KeyboardHardware` to `kaleidoscope::Device` and `Kaleidoscope.device()`.
- Deprecate Model01-TestMode, and turn it into a no-op.
- Use the `auto &serial_port = Kaleidoscope.serialPort();` pattern for examples where that makes sense.

This separates a big chunk of #695 out into an individually reviewable piece. None of the above introduce any user-visible breaking changes. `ATMegaKeyboard` got moved, and we do not provide a backward compatibility layer there, but that's for hardware plugin implementors really, and it will be completely going away with #695 anyway.

### CODE REVIEW

**Comment by obra** [comment]
Thanks so much for splitting this apart!

**Comment by obra** [comment]
Notes I sent @algernon outside of GH: 

This is going to be a little pedantic, but I genuinely believe it is going to save us hours of pain later: https://github.com/keyboardio/Kaleidoscope/pull/710/commits/216b3ec0d76e35e3c1d6f30fcd89110c183cf452

* the deprecations should be broken out into their own commit
* 
For technical reasons, Kaleidoscope.device() wraps
kaleidoscope_internal::device,  --- should get reworded to explain the technical reasons.

https://github.com/keyboardio/Kaleidoscope/pull/710/commits/81d39aa70b836a3ad48d90a1ff24136496f1a5f9 - we ought to add the new hardwaretestmode to the example to replace the one we removed

**Comment by algernon** [comment]
Broke out the deprecations into their own commit, updated the device wrapper explanation, and updated the Model01 example to use HardwareTestMode.

Update force-pushed.

**Comment by obra** [comment]
Great. If travis comes back green, please merge :)

**Pull request merged**
