### PR TITLE
Update Draft

### PR DESCRIPTION
**Pull request by arleym**
I don't have write access, but through conversation with @Jennigma in the forum I've made a few changes, making PR as requested.

- I gave a first pass up to the Editing Keymaps part, then skimmed after there.
- I rearranged some sentences to try to fit more with the "voice" of the Keyboardio brand from its website, to the emails and tweets. It's a soft, friendly and inviting voice. Specifically I used a lot more "We", and tried to gracefully include lines like "uncompromising typists" and "heirloom-grade" (these distinctions left a powerful first impression on me). To be honest, I could spend A LOT more time doing that brand writing, it's so much fun. If there are parts that could be more "branded" let me know.
- I changed a few instances of "Keyboardio" to "Model 01", but perhaps not consistently, when I saw that "keyboardio" is lowercase in the Arduino board manager I wondered if I have over capitalized. If I thought a part of the software could apply to future Keyboardio-brand products I left it as "Keyboardio", and if it seemed very specific to this product I used "Model 01".
- I softened some parts, like removed the IDE part in the first paragraph, moving that to the Arduino introduction below.
- The only completely-removed line was about requiring cleverness and following instructions. I feel like those aren't required. The offers for support I've seen online suggest the non-clever would also get the help they need! Besides, the non-clever just use whatever flavour of rubber domes Dell is shipping this month amiright?! haha.

### CODE REVIEW

**Comment by Jennigma** [comment]
hmm. I *think* if I accept this pull it goes straight into master, but I would rather pull it into this branch and work on it with you there: 

https://github.com/keyboardio/Kaleidoscope/blob/jenndocs-171010/doc/DRAFT_Intro_Docs.md

can you see the jenndocs-171010 branch? Am I misunderstanding?

**Comment by arleym** [comment]
I might be doing this the weirdest way possible, I was doing the edit in the Github gui, not with proper git and markdown. Do you have a way of declining this? Maybe we can start over. I'm not a member of this repo, so I didn't see a git clone option anywhere. Hashtag Github noob.

**Comment by obra** [comment]
@Jennigma is there a reason _not_ to take his changes onto master and then merge them to your branch?


@arleym - You don't need to be an org member to fork your own clone of a repo, you just need to be logged in.

Lemme go create a new PR with this content on @Jennigma's branch

**Comment by obra** [comment]
(Oh, actually, you already created a fork and a branch with the patch, @arleym) so it's just a new PR.

**Comment by obra** [comment]
Created the PR @Jennigma wanted using https://github.com/keyboardio/Kaleidoscope/compare/jenndocs-171010...arleym:patch-1

It's now #208 

Closing this one.

**Comment by Jennigma** [comment]
@obra I didn't want to incorporate @arleym 's changes without some refinement. I think that means I don't want to merge them into master, but rather into a branch, correct?

**Comment by obra** [comment]
Sure. Though another way to do that is to discuss them in the PR thread and
have @arleym update based on your feedback.

(As a side note, the "DRAFT" on the filename should probably go away and
the docs should be marked as a draft inside the file. It's nicer to not
have file locations change based on the content's status if we can avoid
it. (If I post a link to the install instructions now, it'll be a 404 once
the DRAFT label gets removed.)

**Comment by Jennigma** [comment]
@obra I hear your comment about "Draft". Do you want this to remain a monolith in docs, or should I break it up into wiki pages? 

(feeling ok enough to work some, and bored silly from bed rest. I have my bed set up with my laptop and a monitor on a table, and the keyboardio halves in whatever position seems most comfy for my arms from moment to moment. Definitely works better than a laptop for bed rest. )

**Comment by obra** [comment]
wiki pages would be awesome

**Comment by Jennigma** [comment]
Alrighty. Should i locate them in the Model 01 directory, or in Kaleidoscope?

**Comment by obra** [comment]
i think that in general, kaleidoscope is probably right?

**Comment by Jennigma** [comment]
ok. I'll get pages up based on what I've been doing, and then we can figure out how to merge with what's there. I'll make sure it's sensible and not duplicative, so it (hopefully) won't be confusing for new folks this weekend.

**Pull request closed without merging**
