### PR TITLE
EEPROM storage abstraction

### PR DESCRIPTION
**Pull request by algernon**
The goal here is to abstract away our use of EEPROM, so that hardware that doesn't use EEPROM, but has other means of persistent storage (SAMD and ARM in general) will be supported too, as long as they provide the necessary APIs.

This is a work in progress, draft PR, because there are a number of things I want feedback on.

First: naming. Currently, the accessors are called `KeyboardHardware.storage.foo()`. That sounds overly verbose to me, and I'm tempted to name it `PersistentStorage.foo()` instead, outside of the `KeyboardHardware` class - but still shipped by the hardware plugins.

One of the reasons I'm considering moving it outside of `KeyboardHardware` is that I tried to do the same thing as in #611, the curiously recurring template pattern, by having `kaleidoscope::Hardware` be templated, and `.storage.foo()` calling `device.().storage.foo()`, but then I get errors like this:

```
.../Kaleidoscope/src/kaleidoscope/Hardware.h:336:20: error: cannot call member function 'Device_& kaleidoscope::Hardware<Device_>::device() [with Device_ = kaleidoscope::hardware::keyboardio::Model01]' without object                        
       return device().storage_.update(idx, val);
```

Not sure if moving outside would help, mind you, but I'm gonna try nevertheless.

### CODE REVIEW

**Comment by noseglasses** [comment]
What about giving the `Hardware` base class a `storage()` accessor that just forwards `device().storage_`? Then you can write `KeyboardHardware.storage().foo()`. Due to your CRTP implementation, the base class is now fully aware of the actual type of `storage_`.

You can e.g. write
```cpp
auto &storage() -> decltype(this->device().storage_) { return this->device().storage_; }
```
[I always use the `this->` in my other projects because it nicely emphasizes that e.g. `device()` is not a global function.]

Is it possible that we will have keyboards that come with different types of storage? Like keyboards having different types of LED sets (keys, indicators, underglow...)? How to support those?

As a sidenote, I would recommend against exposing any of the data members of the hardware class or their derived classes directly but to provide inline accessors instead.

**Comment by algernon** [comment]
> Is it possible that we will have keyboards that come with different types of storage? Like keyboards having different types of LED sets (keys, indicators, underglow...)? How to support those?

Storage here is supposed to mean a place where we can store persistent configuration, an abstraction over EEPROM. So instead of `EEPROM.get`, one would use `KeyboardHardware.storage().get`.

And yes, there are boards we want to support that don't have EEPROM, only via an emulation layer (anything ARM, basically), and thus we either ship an `<EEPROM.h>` for them (ugly, since it should be in the ArduinoCore for the board, but isn't), or we use an abstraction and let the hardware plugins provide the storage implementation.

> As a sidenote, I would recommend against exposing any of the data members of the hardware class or their derived classes directly but to provide inline accessors instead.

Agreed. New stuff is only exposed because I didn't find a way to put them behind accessors yet.

**Comment by algernon** [comment]
> ```c++
> auto &storage() -> decltype(this->device().storage_) { 
>   return this->device().storage_; 
> }
> ```

Putting this in `kaleidoscope::Hardware` (the base class), and having a `storage_` member in `Model01`, I get:

```
.../Kaleidoscope/src/kaleidoscope/Hardware.h:319:31: error: invalid use of 'this' at top level
   auto &storage() -> decltype(this->device().storage_) {
                               ^
.../Kaleidoscope/src/kaleidoscope/Hardware.h:319:31: error: invalid use of 'this' at top level
.../Kaleidoscope/src/kaleidoscope/Hardware.h:319:22: error: 'storage' function with trailing return type has 'auto&' as its type rather than plain 'auto'
   auto &storage() -> decltype(this->device().storage_) {
```

If I remove the `this` from `decltype`, I get further, and only the last error remains. If I switch `storage()` to `auto`:

```
.../Kaleidoscope/src/kaleidoscope/Hardware.h:319:8: error: invalid use of incomplete type 'class kaleidoscope::hardware::keyboardio::Model01'
   auto storage() -> decltype(device().storage_) {
```

I'm afraid this is way beyond my C++ knowledge at the moment.

**Comment by noseglasses** [comment]
I didn't find time to checkout why this does not work as expected (although I'm curious but AFK).

For the time being you might just leave the `storage()` accessors in the derived classes.

**Comment by obra** [comment]
I'm happy with 'storage' rather than persistentStorage. Storage implies some amount of persistence.

**Comment by algernon** [comment]
Should I go with `Storage`, a global object, or `KeyboardHardware.storage()` instead? The former is easy to do, code isn't terribly complicated either. The second might mean better encapsulation, but the code for that is a tad ugly, because I couldn't figure out yet how to move `storage()` to `kaleidoscope::Hardware` yet, so it has to be copied to every hardware class for now, which is awkward, and feels wrong.

**Comment by noseglasses** [comment]
>.../Kaleidoscope/src/kaleidoscope/Hardware.h:319:8: error: invalid use of incomplete type 'class >kaleidoscope::hardware::keyboardio::Model01'
>  auto storage() -> decltype(device().storage_) {
>
> I'm afraid this is way beyond my C++ knowledge at the moment.

I had to do some research on this topic. It been a while since I last worked with the CRTP idiom, though I rely on it heavily in another code I am working on. Sorry for suggesting something that actually can't work as I expected it.

And here is why:

The thing is that the derived class must be [complete](https://en.cppreference.com/w/cpp/language/type) at the point when the base class that it inherits from is instantiated.
```cpp
class DerivedHardware : Hardware<DerivedHardware> { ... }
```
This means that the only place where the Base class may rely on inventory defined in `Derived` is within function implementations because those are instantiated later. it is not possible to use typenames from the derived class in `Base`'s function signatures (return type, argument types). That's what we tried for the `Hardware` class' `storage()`'s return value. The `decltype(this->device().storage_)` construct would rely on incomplete information.
```cpp
template<typename DerivedHardware__>
struct Hardware {
   // typedef typename DerivedHardware__::SomeType; // won't work
   // typename DerivedHardware__::SomeType doSomething() { ... } // won't work
   void doSomething() { 
      typedef typename DerivedHardware__::SomeType SomeType; // works
      SomeType st;
      st.doSomething();
   }
};

struct DerivedHardware : public Base<DerivedHardware> {
   typedef int SomeType;
};
```

In our concrete use case, this means that the `Hardware` class cannot use the derived hardwares's storage type as a return value for a forwarding `storage()` directly.

There is, however, a workaround that involves a helper template class (`DerivedHardwareInventory`).
```cpp
template<typename DerivedHardware__>
struct DerivedHardwareInventory
{};

template <typename DerivedHardware__> 
struct Hardware
{
    DerivedHardware__ &derived() { return static_cast<DerivedHardware__&>(*this); }

    typedef typename DerivedHardwareInventory<DerivedHardware__>::StorageType StorageType;

    StorageType &storage() 
    {
        return this->derived().storage_;
    }
};

// In SomeStorage.h

struct SomeStorage {
   void doSomething() {}
};

// In DerivedHardware.h

class DerivedHardware; // forward declaration necessary for the below
                                      // specialization of DerivedHardwareInventory

template<>
struct DerivedHardwareInventory<DerivedHardware>
{
    typedef SomeStorage StorageType;
};

struct DerivedHardware : Hardware<DerivedHardware>
{
    SomeStorage storage_;
};

int main(int, char **) {
    DerivedHardware h;
    h.storage().doSomething();
}
```
So this would mean that every derived hardware class would supply a specialization of `DerivedHardwareInventory`, that could simply typedef the storage type and also the types of any other of its members that the base Hardware class needs to use as part of a function signature.

Not pretty but at least a solution where the information is stored close by.

**Comment by noseglasses** [comment]
i would really opt for the encapsulation solution instead of the global `Storage` thing. And if you really want to go the global way, could you call the instance at least `storage`? There are already so many global instances (plugins, hardware, ...) that look like types.

**Comment by algernon** [comment]
I'm fine (and prefer) encapsulation too, just didn't see how to do it. Now that I do, that's the route I'll take. Thanks for all the info!

**Comment by algernon** [comment]
Getting there!

The current branch has `storage_` in the final hardware class, but `storage()` in `kaleidoscope::Hardware`. Except for `ATMegaKeyboard`, which includes `storage_` so the final classes don't have to.

I introduced a `WITH_STORAGE(vendor, className, storageType)` macro to ease some of the boilerplate requirements. This... is a bit of a hack, but I couldn't figure out how to do a template specialization for `kaleidoscope::HardwareInventory` from another namespace (ie, from `kaleidoscope::hardware::vendor`). Things would be a little easier if we could do that, but I'd still use a macro.

I'm not happy with the macro name, any suggestions are more than welcome.

**Comment by noseglasses** [comment]
What do you think about writing the macro arguments of `WITH_STORAGE` uppercase? That would make it easier to keep track of what is a parameter and what not.

The macro is ugly but anyway a good idea as it wraps up things nicely.

**Comment by algernon** [comment]
> What do you think about writing the macro arguments of `WITH_STORAGE` uppercase?

Good call, thanks!

**Comment by algernon** [comment]
Marked as ready for review.

**Comment by algernon** [comment]
Just tested this on SAMD, and there are a few places where `<EEPROM.h>` is still used, going to clean those up in a bit.

**Comment by algernon** [comment]
A'ight, this should be complete now.

**Comment by algernon** [comment]
Remember I said this is ready for review? I was wrong. Fixes incoming.

**Comment by obra** [comment]
@algernon - is this now properly ready for review?

**Comment by algernon** [comment]
Once I rebased on top of current master to fix the conflicts, yes, this should be ready for review.

**Comment by algernon** [comment]
Rebased, it's ready for review. Thanks for the reminder!

**Comment by obra** [comment]
Looks pretty good to me. @noseglasses anything you'd like to see different?

**Comment by noseglasses** [comment]
I don't have much time right now so I cannot really answer this. I'm sure I can have closer look tomorrow and see how this could play together with the requirement to have a separation between hardware implementation and specification as needed for the virtual hardware.

**Comment by obra** [comment]
@noseglasses - Tomorrow's fantastic. Thanks :)
ᐧ

**Comment by noseglasses** [comment]
In general this PR looks great.

The `HardwareInventory` template structs are quite similar to the `*_Spec` classes I intented to use for the Virtual hardware (e.g. [Model01_Spec.h](https://github.com/CapeLeidokos/Kaleidoscope/blob/pr_virtual_build_fix/src/kaleidoscope/hardware/keyboardio/Model01_Spec.h)). Their purpose of sharing inventory between classes is slightly different but the approach of separating general description/specification from implementation is similar.

If the `HardwareInventory` structs of all hardware classes would be moved to individual headers, they could be used by the Virtual hardware, without pulling in any undesired implementation details. Thus, we could use those instead of my `*_Spec` classes and move the `*_Spec`s' inventory over to the hardware inventory templates. Users wouldn't notice the new spec-headers as they are automatically pulled in by the hardware-headers. Thus, it wouldn't hurt us too much to add additional files.

[Here](https://godbolt.org/z/FDt7sl)'s an example that demonstrates how the `HardwareInventory` structs could be used event though some of their typedefed inventory remains undefined. 

This approach works as C++ only requires classes to be fully declared at the point where they are used. A class can, thus, have undeclared typedefs. As long as only the physical hardware classes use those typedefs and the respective definition headers are included in the same scope, everything will work find.

C++ allows template specializations to be derived from any arbitrary type. This would allow us to share parts of the inventory via inheritance.

```cpp
template<typename _T>
struct HardwareInventory {};

class SharedInventory {};

template<>
struct HardwareInventory<int> : public SharedInventory {};
```

I am not perfectly happy with the name `HardwareInventory`, though. That's because I would call `matrix_rows` rather a property than an inventory of the hardware. The same holds for the typedefs as those are rather the type of the inventory than the inventory itself. But I didn't have any better idea than `HardwareProperties` instead of `HardwareInventory` which doesn't sound completely right either. 

What's your opinion?

**Comment by noseglasses** [comment]
I've thought quite a lot about the hardware class design recently to find ways to support the virtual hardware and also to incorporate @algernon's work on hardware modularization with respect to bootloaders and EEPROM. Please fine a respective proposal here: https://github.com/keyboardio/Kaleidoscope/issues/665

**Comment by algernon** [comment]
This has now been rebased on top of #695 and #611. There are a few things left to do once those two are merged:

- [ ] Introduce an `AVRDeviceDescription` that includes the storage parts on top of the base device description. Many of our current devices will just use that as-is, and this will reduce repetition.
- [ ] Document the driver, at least a bit.

**Comment by algernon** [comment]
For ease of development, I folded this into #695. We may end up removing this part from there, at which point I will update the PR. But for the latest working code, see #695 for now.

**Comment by algernon** [comment]
This has been completely folded into #695, closing this one.

**Pull request closed without merging**
