### PR TITLE
Remove V1 plugin API compatibility from our hooks

### LINKED ISSUE #1005: Ancient compat stuff is hanging around from before the INIT_PLUGINS system came into being; it should be removed
in `src/kaleidoscope/hooks.cpp`:
```
// The following weak symbols are overwritten by
// using the KALEIDOSCOPE_INIT_PLUGINS(...) macro
// in the the firmware sketch. Their only purpose is
// to provide backwards compatibility during the transition
// from the old implementation of the hooking/plugin system
// to the new one. The weak symbols ensure that there
// are no undefined symbols if KALEIDOSCOPE_INIT_PLUGINS(...)
// is not used. This allows legacy sketches to be used
// during the transition phase.
```

### PR DESCRIPTION
**Pull request by algernon**
This does two major things:

- Makes `KALEIDOSCOPE_INIT_PLUGINS()` usable with an empty list, in order to allow us to make it mandatory.
- Drops the weak symbols we kept around in `kaleidoscope/hooks.cpp` for V1 API compatibility.

We needed those symbols even for V2, for sketches that did not use `KALEIDOSCOPE_INIT_PLUGINS()`, and we had some of those, even in our examples, because they didn't use any plugins, and we couldn't have an empty list for the macro.

See the individual comments for details on how this is all implemented.

Fixes #1005.

### CODE REVIEW

**Comment by algernon** [comment]
Looks like I need to fix up some of the gtest stuff too. Should be straightforward.

**Comment by algernon** [comment]
AHA. I see. We need a slightly smarter dummy plugin: in the old system, without `KALEIDOSCOPE_INIT_PLUGINS()`, we fell back to the compat code, which had all hooks return `EventHandlerResult::OK`. Without that fallback, we.. don't have code for the handlers. Not quite sure what happens then, but it's... probably not what we want.

In the end, we may end up re-implementing the weak symbols in a different way, in which case we might just stick to the existing one. The argument-less `KALEIDOSCOPE_INIT_PLUGINS()` is still worth it, though.

**Comment by algernon** [comment]
...can't stick to the existing one, because using the dummy plugin will shadow the weak symbols. So we need a smarter dummy.

**Comment by algernon** [comment]
*sigh*

Moving the fallback code to a smarter "dummy" plugin continues to error out on gtests. Pushed my latest state, but this needs more work.

**Comment by obra** [comment]
honestly, we’ve gotten to the point where this solution is probably worse than the problem and updating the comments to explain why we actually have the code there feels like a reasonable choice. If it’s not just legacy stuff that needs to get yanked out maybe it should stay

**Comment by algernon** [comment]
Closing, as we've agreed not to go down this path.

**Pull request closed without merging**
