### PR TITLE
System control keys on mac

### PR DESCRIPTION
**Pull request by obra**
System control keys on macOS were not functional, since we were deferring the press until immediately before release, which doesn't work for how Apple handles OSC System Control keys. Instead, we should send one press event at press time and one release event at release time.

### CODE REVIEW

**Comment by algernon** [comment]
Looks like this is already on master?

Looks sane to me nevertheless.

**Comment by obra** [comment]
Ugh. Unintentional. Glad it got approved, then ;)

**Comment by gedankenexperimenter** [comment]
Looking at the code, I believe there's still a bug. If the user rolls over from one system control key to another, the second one will get released as soon as the first one gets released.

1. Key `A` toggles on -> `A` report sent
2. Key `B` toggles on -> `B` report sent, clobbering `A` (correctly)
3. Key `A` toggles off -> empty report sent (incorrectly indicating that `B` was released)
4. Key `B` toggles off -> another empty report sent

When a system control key is released, it shouldn't unconditionally send the empty report. Instead, it should check to verify that the released key is the same as the last one that was sent. To do this right, it's necessary to store that state, probably in KeyboardioHID.

**Comment by obra** [comment]
Hm. That's an interesting corner case. I'll open up a new, separate
issue for it.  I agree that it should be fixed, but it's also
exceedingly unlikely that anyone will run into it. As far as I know,
there just aren't that many system-control keys that are actually
supported by host operating systems.

**Comment by obra** [comment]
Opened #840 to track the issue @gendankenexperiementer noticed.

**Pull request merged**
