### PR TITLE
Use eager reporting when debouncing

### PR DESCRIPTION
**Pull request by p00ya**
If a key has been in a stable and then changes, report that change immediately and then wait for a cooldown period before reporting any additional changes.  This reduces latency for registering the initial keypress (important to some gamers).

It would be unusual for this to introduce chatter, since mechanical switches only tend to be noisy immediately after a key press or release.  However, if there are other background sources of electrical noise (not localized to switch actuation), this could result in spurious matrix changes.

This change does not introduce any additional persistent state, although it does add an additional parameter to the debouncer to distinguish between the last raw state and the last debounced state.

It also fixes a bug whereby all rows in the matrix would be rewrittenfor every row that changed due to a mis-nesting of loops.  However,
it now writes to the matrix state unconditionally (which didn't seem like an important optimization, though please let me know if it is).

I made standalone unit tests for the new debounce function, but they're not included in this commit (I couldn't find the existing tests for the ATmega driver in Kaleidoscope, if you let me know where they are I can extend them).  I'd be grateful for additional manual testing.

Note these changes will conflict with #878, but could be ported to the new debouncer location there with a little bit of a change in the API.

### CODE REVIEW

**Comment by algernon** [comment]
> It would be unusual for this to introduce chatter, since mechanical switches only tend to be noisy immediately after a key press or release. However, if there are other background sources of electrical noise (not localized to switch actuation), this could result in spurious matrix changes.

This is the part I'm a little worried about, because often times during a game, one's going to press keys nearby, which might "echo" a bit, especially if the key is hit hard, and causing spurious matrix changes in the process.

_Ideally_, we would be able to choose the debouncing method at runtime, or at least at compile time... not sure we're there yet, but if that'd be in place, I would be much less worried.

Then again, this is just a hunch, I have little clue about how the hardware works in practice, so what I said above might even be complete nonsense, in which case, I'm sorry for the noise.

**Comment by p00ya** [comment]
As a data point, the QMK folks use symmetric eager debouncing for many keyboards.  e.g. ZSA's Ergodox EZ build uses eager-per-row (really per physical column), which I've been using without any chatter with Kailh and Cherry MX switches (though they have a cooldown time of ~30ms by default!).  I think they only use per-row as a workaround for their huge counters (full 16-bit timer value) vs the 2-bit counters in Kaleidoscope - I don't think it systematically reduces noise since it only aggregates in one dimension anyway.

In practice, in QMK with eager_pr I started noticing chatter with aggressive (<10ms) cooldowns.  I've *never* noticed cross-talk (even with the 10ms `DEBOUNCE`).  I think that being conservative with the cooldown is offset by the eager reporting, so overall the keyboard feels stable while being responsive (the HID and OS latency becomes more significant).  But you do need more bits (maybe 2 isn't enough).

I'm not lucky enough to own keyboardio hardware though, so I would certainly welcome physical testing by banging away on a Model01.

**Comment by obra** [comment]
First up, thanks so much for the contribution!

I've previously played with eager debouncing like this.  @algernon is right that we've had reports (from @mattvenn at dygma) of single individual spurious reads due to unknown environmental issues. 

I don't think it's the right standard default, but I'd love to have it available as an alternate debouncing algorithm.

Most of our work around debouncing has lived in the Model 01's keyscanner library, which runs on the attiny chips that do the matrix scans and debounce. https://github.com/keyboardio/avr_keyscanner is where that code lives, along with a whole bunch of single-key recorded keyscan data. You can find the debouncing algorithms we've played with here: https://github.com/keyboardio/avr_keyscanner/tree/master/firmware

What I'd love to see is for the debouncing algorithm to be pluggable or toggleable.  For "general computing use", a more conservative debouncer feels like the right choice, but I 100% agree that having a 'gaming mode' debouncer would be a huge win for users.

As to unit tests: we've recently (finally) gotten gtest up for end to end simulator testing, but don't currently have a decent framework in place for unit tests. That's something I'd be thrilled to see improved.

**Comment by p00ya** [comment]
Good to know you've already been experimenting with other debouncing algorithms.

Regarding pluggable debouncing, it seems to make more sense for me to wait for #878 to go through (which should establish a polymorphic debouncer interface that can then be switched in future) than to adapt this PR, and then you can use that from both the attiny and ATmega drivers.  It also looks like you don't really need this particular eager implementation either since you have similar ones for attiny already. :)

It totally makes sense to prioritize reliability over report latency (especially since you're selling the hardware!).

I would add that the Dygma report seems worth investigating more deeply... like I said my Ergodox EZ is already using eager with QMK (so any new read such as a press from idle state will be immediately reported) and I don't get any spurious press events or cross-talk, so I'd be seriously considering either defects either in the Raise hardware or maybe races in Kaleidoscope (the comments on `readCols` already indicate it's a bit fragile with respect to races!).

Feel free to close the PR, I'll keep the branch around for a bit in case you like the implementation since the bitwise logic is a little subtle :)

**Pull request closed without merging**
