### PR TITLE
Future-proof our driver & device helper macros

### PR DESCRIPTION
**Pull request by algernon**
We currently have `ATMEGA32U4_KEYBOARD` as a helper macro to make it easier to create derived keyboards, but it takes a fixed, set amount of arguments, so anytime we want to add a new device property, we'd have to create a new macro, which doesn't scale.

So instead of having one macro with many arguments, lets introduce a different kind of helper macro: one that abstracts away the boring parts, but still lets you assemble the device descriptions piece by piece. This is more verbose, indeed, but it is also clearer, and easier to extend. We can just add new properties for devices that need it, and leave the rest alone without breaking anything.

#### Previously

```c++
ATMEGA32U4_KEYBOARD(
  Atreus2, Caterina, "atreus",
  ROW_PIN_LIST({PIN_F6, PIN_F5, PIN_F4, PIN_F1}),
  COL_PIN_LIST({PIN_F7, PIN_E2, PIN_C7, PIN_C6, PIN_B6, PIN_B5, PIN_D7, PIN_D6, PIN_D4, PIN_D5, PIN_D3, PIN_D2})
);
```
#### With the new helpers

```c++
DECLARE_ATMEGA32U4_KEYBOARD(
  Atreus2,
  WITH_KEYBOARD_SHORTNAME("atreus");
  WITH_BOOTLOADER(avr::Caterina);
  WITH_ATMEGA_KEYSCANNER(
    ROW_PIN_LIST({PIN_F6, PIN_F5, PIN_F4, PIN_F1}),
    COL_PIN_LIST({PIN_F7, PIN_E2, PIN_C7, PIN_C6, PIN_B6, PIN_B5, PIN_D7, PIN_D6, PIN_D4, PIN_D5, PIN_D3, PIN_D2})
  );
);
```

#### Previously

```c++
struct SplitographyProps : kaleidoscope::device::ATmega32U4KeyboardProps {
  struct KeyScannerProps : public kaleidoscope::driver::keyscanner::ATmegaProps {
    ATMEGA_KEYSCANNER_PROPS(
      ROW_PIN_LIST({ PIN_D0, PIN_D1, PIN_D2, PIN_D3 }),
      COL_PIN_LIST({ PIN_F0, PIN_F1, PIN_F4, PIN_F5, PIN_F6, PIN_F7, PIN_C7, PIN_C6, PIN_B6, PIN_B5, PIN_B4, PIN_D7 })
    );
  };
  typedef kaleidoscope::driver::keyscanner::ATmega<KeyScannerProps> KeyScanner;
  typedef kaleidoscope::driver::bootloader::avr::FLIP BootLoader;
  static constexpr const char *short_name = "splitography";
};

#ifndef KALEIDOSCOPE_VIRTUAL_BUILD
class Splitography: public kaleidoscope::device::ATmega32U4Keyboard<SplitographyProps> {
 public:
  Splitography() {
    mcu_.disableJTAG();
  }
};
#else // ifndef KALEIDOSCOPE_VIRTUAL_BUILD
class Splitography;
#endif // ifndef KALEIDOSCOPE_VIRTUAL_BUILD
```

#### With the new helpers

```c++
ATMEGA32U4_DEVICE(
  Splitography,
  WITH_ATMEGA32U4_DEVICE_PROPS(
    Splitography,
    WITH_KEYBOARD_SHORTNAME("splitography");
    WITH_BOOTLOADER(avr::FLIP);
    WITH_ATMEGA_KEYSCANNER(
      ROW_PIN_LIST({ PIN_D0, PIN_D1, PIN_D2, PIN_D3 }),
      COL_PIN_LIST({ PIN_F0, PIN_F1, PIN_F4, PIN_F5, PIN_F6, PIN_F7, PIN_C7, PIN_C6, PIN_B6, PIN_B5, PIN_B4, PIN_D7 })
    );
  ),
  public:
Splitography() {
  mcu_.disableJTAG();
}
);
```

### CODE REVIEW

**Comment by algernon** [comment]
I'm fairly happy how this turned out, but there's one part I'm not sure about: whether including the - optional - body of the device class _in_ the macro is a good idea. An alternative would be something like this:

```c++
ATMEGA32U4_DEVICE(
  Splitography,
  WITH_ATMEGA32U4_DEVICE_PROPS(
    Splitography,
    WITH_KEYBOARD_SHORTNAME("splitography");
    WITH_BOOTLOADER(avr::FLIP);
    WITH_ATMEGA_KEYSCANNER(
      ROW_PIN_LIST({ PIN_D0, PIN_D1, PIN_D2, PIN_D3 }),
      COL_PIN_LIST({ PIN_F0, PIN_F1, PIN_F4, PIN_F5, PIN_F6, PIN_F7, PIN_C7, PIN_C6, PIN_B6, PIN_B5, PIN_B4, PIN_D7 })
    );
  );
) {
  public:
    Splitography() {
      mcu_.disableJTAG();
    }
}
```

The advantage of this is that formatting the body looks more like C++, and is easier to do that. The disadvantage is that we can't reuse `ATMEGA32U4_DEVICE` for this, and would need a new macro if we want to keep backward compatibility. We could still use `ATMEGA32U4_DEVICE` for the case where we do not need a body, mind you.

**Comment by algernon** [comment]
Another idea, that helps in cases where we have the constructor do some MCU-related setup: we could have MCU properties, and the MCU constructor could do the necessary setup based on those properties.

We'd still need a solution for stuff like the Imago:

```c++
ATMEGA32U4_DEVICE(
  Imago,
  WITH_ATMEGA32U4_DEVICE_PROPS(
    Imago,
    WITH_KEYBOARD_SHORTNAME("imago");
    WITH_BOOTLOADER(avr::Caterina);
    WITH_ATMEGA_KEYSCANNER(
      ROW_PIN_LIST({ PIN_F6, PIN_F5, PIN_F4, PIN_F1, PIN_F0}),
      COL_PIN_LIST({ PIN_B2, PIN_B7, PIN_E2, PIN_C7, PIN_C6, PIN_B6, PIN_B5, PIN_B4, PIN_D7, PIN_D6,  PIN_D4, PIN_D5, PIN_D3, PIN_D2, PIN_E6, PIN_F7})
    );
    WITH_LED_DRIVER(Imago);
  ),
  public:
  void setup();
);
```

...but we'd handle the more common case nicely. I'll add MCU props - if that's deemed useful, I'll lift it out into a separate PR, too.

**Comment by algernon** [comment]
Well, MCU props would either be a breaking change, or we'd need a different class for Prop and Prop-less MCUs. I'll explore that in a separate PR.

**Comment by obra** [comment]
Moving a private discussion to this draft PR.

The more I think about it, the more I think I was wrong when I pushed us toward using macro based metaprogramming to make device implementations appear simpler. We end up with code that's..not quite data and not quite C++. The end result is that while we've gotten to a locally optimized "easy" first hour implementing a device using the macros, doing something more complex is much, much harder, because you need to unwind the macros and then reimplement what they did.

This PR is a fantastic improvement to the status quo and kicks the proverbial football down the field. For a trivial device, the author may end up not having to go from the macros to full C++ definitions. But if they do, we're still running into the same issues.

Folks who would be dramatically helped by the macros would get almost as much value out of a template and a tutorial and would end up with code that's less brittle going forward.

**Comment by algernon** [comment]
Closing this in favour of #868, which removes macro use completely.

**Pull request closed without merging**
