### PR TITLE
Fix out-of-bounds memory accesses resulting from handleKeyswitchEvent()

### PR DESCRIPTION
**Pull request by cdisselkoen**
I think this properly resolves the out-of-bounds memory access problem.  At the very least, observable behavior shouldn't change as a result of this commit.  This does resolve the segfault problem in the virtual hardware, at least for its example firmware.

My current theory is that on the real hardware, the out-of-bounds memory accesses prior to this commit are just so far out of bounds that they're beyond the size of the physical memory in the Arduino, and since we don't have a virtual memory system the hardware just drops them.  For writes that's fine, and for reads, maybe we end up never actually using the data for those keypresses?

Although my solution works, it's possible there's a better solution from someone who understands this part of the code better than me - maybe instead of a bounds check, the keypresses with out-of-bounds (row,col) should never hit this code in the first place.  This PR should probably have review from @obra and/or @algernon before merging.

### CODE REVIEW

**Comment by cdisselkoen** [comment]
I did test this commit on real hardware (and virtual hardware) and didn't see any immediate problems in either case.

**Comment by cdisselkoen** [comment]
Fixed astyle

**Comment by algernon** [comment]
Looks good to me. Events with `255,255` *must* reach this part of the code, because we use these to say "we don't know the location where this fired from" in certain places, which do want some kind of action to be taken.

Thus, the bounds check is correct, it belongs here, and it covers just the right amount of code.

**Comment by obra** [comment]
<3

**Pull request merged**
