### PR TITLE
Simplify Escape-OneShot plugin

### PR DESCRIPTION
**Pull request by gedankenexperimenter**
After reading the discussion on key masking in #884, I realized that Escape-OneShot could be simplified even further. Then I'm pretty sure I found an unreported corner-case bug in its logic, which is also fixed here.

I removed the unnecessary `did_escape_` boolean, and instead changed Escape-OneShot so that it is only triggered if the `escape` key has toggled on.

Additionally, I changed the conditions to agree better with the docs. Previously, if there was a sticky OneShot key, the `escape` key would cancel OneShots even if a OneShot key was being held, contrary
to the docs. I suspect this was a logic error in the rather tricky conditional that was being used.

### CODE REVIEW

**Comment by algernon** [comment]
Unfortunately, this doesn't work the way it should: when having a OneShot active, and I press `Esc`, it should deactivate OneShot, and _not_ send Esc, not even if I hold the key a little longer.

With these changes applied, even a very quick tap results in Esc being registered nevertheless.

**Comment by gedankenexperimenter** [comment]
I had forgotten the details of how the `live_composite_keymap_[]` cache works, and how much trickier it is to deal with the not-so-event-driven Kaleidoscope. With a call to `layer.updateLiveCompositeKeymap()`, which is what I was incorrectly assuming would happen by modifying `mapped_key`, I believe it should work. It's a bit odd to manually insert a `Key_NoKey` value there, and it does mean that plugin event handler hooks will get called with that as the mapped key value, but none of them should actually do anything with a `Key_NoKey` (except MagicCombo?).

**Comment by gedankenexperimenter** [comment]
I got a chance to test my revised version, and it works on non-sticky OneShot keys, but not sticky ones. I think this is because of a bug in OneShot. According to the docs, `OneShot.isPressed()` returns `true` any time a OneShot key is held, but this is not the case. In particular, if there are any sticky OneShot keys, the `state_[i].pressed` bit will be set even after the key is released. Before I submit a PR to fix this, though, I'd like to know from @algernon if there's anything other than Escape-OneShot that uses the `isPressed()` method is used by. I don't see any other occurrences of it in Kaleidoscope proper, but I'm not confident that I would find everything by doing the primitive searches that I know how to execute.

**Comment by gedankenexperimenter** [comment]
I'm working on more substantive changes to both this and OneShot itself, so I'm going to close this PR, at least for now.

**Pull request closed without merging**
