### PR TITLE
EscapeOneShot: Run-time toggleability, and Focus-based configuration

### PR DESCRIPTION
**Pull request by algernon**
Ideally, we'd like to ship firmware files with Chrysalis with the `EscapeOneShot` plugin enabled - but to do that, we need to be able to toggle the plugin on and off at runtime. So these patches do that: make it possible to toggle it, and then add a new plugin, `EscapeOneShotConfig` (in the same library, for convenience, but separate, so it's completely optional), which implements the Focus bits.

I'm setting this to a draft until I get the Chrysalis parts done and tested, to see if we need anything else.

### CODE REVIEW

**Comment by algernon** [comment]
Pushed another commit, which I'd like to have some feedback on, as it slightly alters the behaviour of the plugin: it now treats `Key_OneShotCancel` as a cancel key when seen, even if not set up so via `EscapeOneShot.setCancelKey()`. The primary reason for that is to make it easier to use with Chrysalis: if one wants to use a dedicated key, all they have to do is place it on the keymap, rather than doing that _and_ setting it up as a cancel key.

Another reason for this is that the initial Chrysalis side of this will not offer selecting the cancel key: it will either be `Escape`, or `Key_OneShotCancel`, because offering key selection would be a bigger task than what I have the resources for at the moment.

**Comment by algernon** [comment]
On the other hand, Chrysalis _will_ have to set the cancel key, to disable `Escape` cancelling oneshots. So there will be special code anyway. But the change still feels right, because the dedicated key is completely useless otherwise.

**Comment by obra** [comment]
That makes sense to me

**Comment by algernon** [comment]
Tested this with Chrysalis, and it does what we need, so marking as ready.

**Comment by gedankenexperimenter** [comment]
I want to apologize for not noticing or commenting on this sooner.  The name `OneShotCancelKey` was decided, I believe, in a conversation I had with @obra about both that name and the names of the special keys now in the `OneShotMetaKeys` plugin.  I had started with names beginning with the `Key_` prefix, but @obra said that was not intended to apply to all constants of type `Key`, but was originally meant for Keyboard HID keys.  Note that Consumer Control and System Control keys do not begin with `Key_`.

I'm all for consistency, and I have no particular objection to the name change.  The other special OneShot keys are currently named `OneShot_MetaStickyKey` and `OneShot_ActiveStickyKey`, so those should either also change, or this one should get named `OneShot_CancelKey`, to match the pattern `<plugin_name>_<key_name>Key` (or some other pattern).

**Pull request merged**
