### PR TITLE
[WIP] A new CLI build system

### LINKED ISSUE #497: Rethinking kaleidoscope-builder
For a while now, I've been pondering about replacing the current `kaleidoscope-builder`, for a number of reasons. I think the time has come when we should no longer push this task further down the roadmap, as the issues with the builder are showing. The most apparent problem is that it doesn't really support multiple keyboards: most of it is hacked in, and the Model01-centric stuff still leak through (try flashing anything else with it, for example... :P).

Before going into specific ideas, I'd like to enumerate the problems *I* see with `kaleidoscope-builder`:

- It doesn't have much support for boards other than the Model01. Anything else needs some tweaking in a `.kaleidoscope-builder.conf` somewhere. This is especially painful when flashing, as the only built-in way is to use the Model01 flashing process, with status messages and errors specific to that keyboard.
- It provides no way of selecting variants (which is an important thing for the Atreus, for example).
- The way the configuration is put together is... non-intuitive. The ordering is all wrong in places, making it hard to debug, and to figure out what goes on.
- Being a shell script, it's not all that portable to other platforms (especially painful on Windows).
- It's fragile.
- It is slow, and does not support building in parallel.

### PR DESCRIPTION
**Pull request by algernon**
The `kaleidoscope-builder` tool is starting to show its age, and the mistakes made during its design: it didn't have first-class support for different hardware, and it was a lot more brittle one would have liked.

The new build system is much more modular, has first-class support for different hardware, and wraps the tools used much more thinly. It's also less code, too.

This is the Kaleidoscope part of the update, the real deal is in keyboardio/Kaleidoscope-Build-Tools#5, together, they fix #497.

### CODE REVIEW

**Comment by algernon** [comment]
While I consider this good enough, it would need some more through testing, and possibly more / better documentation. It can be used to compile every example in the tree, it's sufficient to compile my own sketch too, which has third-party plugins, and a setup much more complex than the factory firmware or the examples. (It can also compile the Model01 factory firmware too, by the way.)

There's one major change: `make flash` will not always call `build`: it will flash the latest compiled firmware, if one exists, and will only recompile if it can't find one. `make build flash` will always rebuild, however.

The new system lacks a few things `kaleidoscope-builder` had, namely flashing with a programmer or with a bootloader. Those should be fairly easy to re-add, should it be needed.

**Comment by gedankenexperimenter** [comment]
I'd like to know whether it is a question of _if_ or _when_ this PR (or something similar or based on this PR) will be merged. It looks like a big improvement on `kaleidoscope-builder`.

**Comment by algernon** [comment]
It's a question of *when*, and it largely depends on when I get around to update it.

**Comment by gedankenexperimenter** [comment]
In that case, I'll see if I can find time to try it out, and provide some feedback.

**Comment by algernon** [comment]
> Also, I will be reworking the system so that there's a single source of Truth with regards to boards: VID, PID, etc should not be duplicated. Rather, there will be a single source, from which we'll generate the boards.txt file too (and check that into git too, to make things easier). The makefiles will either use this source, or be generated from these source themselves too.

I've been thinking about this for the past two days, trying to think of a simple, reasonable way to have single source of truth. For some things (VID, PID) it is easy. For some other things (size limits) its considerably harder, because the same board may have multiple options. And flashing is a whole new level of pain, because of the differences between the flashers themselves, the possibility of the same board supporting different flashers presents a whole lot of combinations.

`boards.txt` and `platform.txt` aren't a good source, because they're not easy to process, unless you're Arduino itself. When it comes to flashing, it's also a horrible way to set the flashing commands (just see the DFU stuff for the Planck).

Makefiles aren't a suitable source of truth, either, because it's not easy to enumerate the options and generate proper `boards.txt` and `platform.txt` files.

So, I have a different proposal: lets have some duplication for now. Once `arduino-cli` is stable, we can transparently replace the guts of our build system to be built upon that, and get rid of the duplication.

**Comment by gedankenexperimenter** [comment]
@algernon and/or @obra — Would you mind commenting briefly on how this PR relates to or would be affected by #591?

**Comment by algernon** [comment]
The improvements in #591 will be incorporated into this one, using the same variable names, so as long as you override stuff via Makefiles or environment variables (as opposed to `.kaleidoscope-builder.conf`), they'll still work. #591 will still be useful until I can finish this one up (and that might take a while, this isn't at the top of my stack at the moment).

**Comment by obra** [comment]
@algernon -  I believe this is obsolete. If not, please feel free to reopen.

**Pull request closed without merging**
