### PR TITLE
Pluggable HID facade

### PR DESCRIPTION
**Pull request by algernon**
Built on top of #278, this moves the HID facade to the [Kaleidoscope-HIDAdatpor-KeyboardioHID](https://github.com/keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID) shim library. We do this so we can replace it, if need be.

In this PR, we include it by default, to be backwards compatible, but all of the symbols in the new library are weak, and can be overridden, which allows one to use another library, if so they wish (at the cost of some symbols not getting optimized out). If/when we break the API, we can remove the default too. For that reason, the examples were updated to pull the library in themselves, to ease migration later on.

### CODE REVIEW

**Comment by obra** [comment]
Would it be possible to pull in the hid library we want to use from the hardware definition rather than from the sketch or from kaleidoscope itself?

**Comment by algernon** [comment]
We could, but that makes it more complicated to replace the HID library for the same board. As in, if I don't want to have BootKeyboard stuff, because it is big, I need space, and all my stuff understand NKRO, that becomes harder.

With the current setup, I can include another header (though, BootKeyboard will still be in, because of the defaults - but if we get rid of the default, then it won't). If we tied the HID to the hardware, I wouldn't be able to do this. Not this easily.

Mind you, doing this kind of resource-saving gymnastics probably means an advanced user, who can hack up a quick hardware definition too...

So if you want, I'll submit another PR.

**Comment by obra** [comment]
Hrm. I'd strongly prefer to keep this pushed down further than the user's
sketch. This shouldn't be the kind of detail they need to be aware of.

-j

**Comment by algernon** [comment]
Fair enough, new PR coming up soon then!

**Comment by algernon** [comment]
I just had a neat idea, a kind of compromise between two goals: primary goal being not pushing this down to the user's sketch; secondary being allowing an advanced user to either change the adaptor, or tweak it.

If we bind it to the hardware like we do with the hardware plugins (via the hardware definition and a macro), then it is not pushed to the user's sketch. If we make parts of the adaptor conditional, an advanced user can set extra flags for the compiler (possible both in the IDE and on the command-line), and tweak it further. Without having to fork code, copy hardware definitions, or anything crazy like that. The cost is a few `#ifdef` blocks in the adapter plugin.

While here, we may as well skip the macro dance, and have the hardware plugin include the adaptor. Most of the time, one will not want to change the adaptor, just tweak it. For all other cases, one can fork the hardware plugin, I suppose.

So, newest proposal, for which I'll be submitting PRs for:

- `Kaleidoscope-HIDAdaptor-KeyboardioHID` to be included by `Keyboardio-Hardware-Model01`.
- All of the `extern` stuff dropped, because they aren't useful anymore.
- A few tweakable knobs to be added: `KALEIDOSCOPE_HIDADAPTOR_KEYBOARD_NKRO_ONLY` will disable the boot fallback when defined (defaults to undefined); `KALEIDOSCOPE_HIDADAPTOR_NO_MOUSEWARP` will disable warp (they'll be noop); `KALEIDOSCOPE_HIDADAPTOR_NO_MOUSE` will disable all mouse stuff. (The latter two will address #257).

**Comment by obra** [comment]
When you say "No Mouse Warp", is what you mean really "No
AbsoluteMouse/Graphics Tablet descriptor"?

If so, it may be better to call it that.

**Comment by algernon** [comment]
Yeah, that's what I mean. `KALEIDOSCOPE_HIDADAPTOR_NO_ABSOLUTE_MOUSE` then. *If* it turns out that `ifdef`-ing its usage out helps.

**Comment by gedankenexperimenter** [comment]
I had the same idea for leaving out certain parts of the HID code yesterday, but I thought all the `#ifdef`s would be too ugly to be acceptable.

I had some other related ideas, but I don't know enough about how the complier optimizes things out to know if they would work.

**Comment by gedankenexperimenter** [comment]
I'd also like to understand how the HID code is dependent on the hardware; it doesn't seem like it has anything to do with the hardware module, but I keep hearing that they're related somehow.

**Comment by algernon** [comment]
> I had the same idea for leaving out certain parts of the HID code yesterday, but I thought all the `#ifdefs` would be too ugly to be acceptable.

Yeah, I was worried about the ifdefs, but they can be kept under control with a little trick or two, see keyboardio/Kaleidoscope-HIDAdaptor-KeyboardioHID#2 for details. Basically, for boot keyboard, I use two new macros: `WITH_BOOTKEYBOARD` and `WITH_BOOTKEYBOARD_PROTOCOL`, that expand differently when boot protocol is disabled: they expand to `if (0)`, thus the compiler drops the entire block that follows. For mouse and absolute mouse, I just have a big `#if` block that implements all the functions in the namespace, and an `#else` branch that implements them as no-ops. This way the ifdefs are reasonably localised, and not spread all over the place. There are three `#if/#else` branches total, which I believe is acceptable.

**Comment by obra** [comment]
"I'd also like to understand how the HID code is dependent on the hardware;
it doesn't seem like it has anything to do with the hardware module, but I
keep hearing that they're related somehow."

The HID implementation is generally fairly tied to the microcontroller
being used for a given device. All keyboards using a 32U4 could use
KeyboardioHID as written. But a keyboard using an ARM of a given type or
something else would need to support that manufacturer's USB implementation.

**Comment by algernon** [comment]
> I'd also like to understand how the HID code is dependent on the hardware; it doesn't seem like it has anything to do with the hardware module, but I keep hearing that they're related somehow.

The best way I can explain is that this is a logical dependency. As in, the adaptor does not depend on the hardware plugin in terms of code. The dependency is in the physical product: if you have a certain keyboard product, you'll want a matching HID adaptor. For example, if your hardware does not support USB, only Bluetooth, you'll want a HID adaptor that does that. Or the other way around. The whole pluggable HID thing grew out of a desire to power bluetooth-enabled keyboards with Kaleidoscope. :)

This is primarily for vendors, not users or developers. Exceptions exist, of course.

(Also, what @obra wrote.)

**Comment by gedankenexperimenter** [comment]
Since the hardware-dependency of the HID library is non-obvious (I still can't find it, and I'm looking for it), perhaps it would be better to call it Kaleidoscope-HID-<hardware-name> to make it clear what microcontroller(s) it will work on?

**Comment by gedankenexperimenter** [comment]
Markdown ate part of my comment, and I didn't notice. It should have read "Kaleidoscope-HID-Atmega32u4" (for example). Or maybe that should be AVR? I still can't tell.

**Comment by algernon** [comment]
It's `HIDAdaptor-KeyboardioHID`, because it depends on the `KeyboardioHID` library. If we rename one, we need to rename the other, too.

I'll leave it up to @obra to figure out if we want to do that.

**Comment by gedankenexperimenter** [comment]
I wasn't referring to the name of the façade library; I meant that "KeyboardioHID" should perhaps give me a hint about its limitations in the name — and be explicit about it in the documentation, which says nothing about hardware dependence. I'll submit an issue over there about this.

**Pull request merged**
