### PR TITLE
Remove the HID_TYPE_* defines

### LINKED ISSUE #350: HID types in key_defs.h rendered useless by new `IS_CONSUMER` value
Prior to https://github.com/keyboardio/Kaleidoscope/pull/242/commits/f57aab5f718d3b47ea2252ec6c006c96cc62eb59, the value of `IS_CONSUMER` was `B00000010` and this was OR-able with the values of the HID types:

```
#define HID_TYPE_CL    B00000000
#define HID_TYPE_LC    B00000100
#define HID_TYPE_NARY  B00001000
#define HID_TYPE_OOC   B00001100
#define HID_TYPE_OSC   B00010000
#define HID_TYPE_RTC   B00010100
#define HID_TYPE_SEL B00011000
```

In fact, the comment line https://github.com/keyboardio/Kaleidoscope/blob/master/src/key_defs.h#L100 still reads:
```
   We need to keep the bottom two bits clear for defining the keys as sysctl / consumerctl
```
… as if the value of `IS_CONSUMER` were still `B00000010`.

However, the value of `IS_CONSUMER` after above PR/commit became `B00001000` and this evidently conflicts with the above HID types as it uses a bit position used by them. That is, currently, after OR-ing, this renders the following pairs of values identical:

* `IS_CONSUMER | HID_TYPE_CL` and `IS_CONSUMER | HID_TYPE_NARY` are both `0b00001000`
* `IS_CONSUMER | HID_TYPE_LC` and `IS_CONSUMER | HID_TYPE_OOC` are both `0b00001100`
* `IS_CONSUMER | HID_TYPE_OSC` and `IS_CONSUMER | HID_TYPE_SEL` are both `0b00011000`

This has already been pointed out by @gedankenexperimenter in https://github.com/keyboardio/Kaleidoscope/pull/242#commitcomment-26441387 but apparently ignored. I'm quite surprised to say the least that such a PR was pulled without having the obvious conflict addressed.

Now it seems that either the HID type markers should be discarded, or their values modified to not conflict with the `IS_CONSUMER` value (and the `CONSUMER` and other stuff that that PR addressed)…

### PR DESCRIPTION
**Pull request by algernon**
These were used in the past, but aren't anymore, and are just confusing to have them here (doubly so with an obsolete comment).

Fixes #350.

### CODE REVIEW

**Comment by obra** [comment]
So, we -should- be acting on the different types of HID keys different. Is there an actual advantage to removing the data?

**Comment by algernon** [comment]
Well, we don't currently act differently on them, and they still appear to work, as far as I can tell. If that is, indeed the case, then the advantage is cleaner code. If I'm wrong, then we should:

1) Update the comment.
2) Fix our consumer/sysctl handlers to do act differently based on hid type.

**Comment by obra** [comment]
If the keys get handled the same way, the spec shouldn't require them to be
called out separately.  I believe that we should be treating OSC
differently than other key types for example. I -think- that they should be
instant press and release. I'd need to go back to the spec to understand
what we should be doing with each type. Certainly, there are a bunch of
weird things we don't really support properly yet. I'd love to start with
the comment getting updated.
ᐧ

**Comment by algernon** [comment]
Closing this one, since the changes aren't good, and I don't have the resources to figure out the best way forward. Having the `HID_TYPE_*` defines doesn't hurt us much, so dealing with them isn't much of a priority right now.

**Pull request closed without merging**
