### PR TITLE
Switch us over from arduino-builder to arduino-cli

### PR DESCRIPTION
**Pull request by obra**
Switch Kaleidoscope to build with a brand new makefile system and arduino-cli.  Users no longer need to install the Arduino IDE.

The readme has been updated with the new usage.

### CODE REVIEW

**Comment by obra** [comment]
@algernon this is ready for test and potentially merge if you approve.

**Comment by gedankenexperimenter** [comment]
I'm trying this out for the first time, and building tests fails:
```
$ make docker-simulator-tests
Arduino user directory /Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user
ARDUINO_DIRECTORIES_USER="/Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user" ./bin/run-docker "make simulator-tests "
Preparing Kaleidoscope and the bundle...
The bundle is coming from /Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user/hardware/keyboardio
./bin/run-docker: line 37: cd: /Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user/hardware/keyboardio: No such file or directory
make: *** [docker-simulator-tests] Error 1
```
I don't see a `.arduino` directory; this looks like an oversight that works for you because you've had one for a while, perhaps?

**Comment by gedankenexperimenter** [comment]
Ah. `make setup`…

**Comment by gedankenexperimenter** [comment]
```
$ make docker-simulator-tests TEST_PATH=tests/plugins/Redial
```
That fails almost immediately.
```
$ make docker-simulator-tests TEST_PATH=plugins/Redial
```
That gets a little bit further. In both cases, I think there's a path being constructed incorrectly. In the latter case, it's:
```
make[4]: Entering directory '/kaleidoscope/testing/googletest/build'
/bin/sh: 1: cd: can't cd to /kaleidoscope/hardware/keyboardio/avr/libraries/Kaleidoscope/testing/googletest/build
```
…and `/kaleidoscope/hardware` doesn't exist.

What's really weird is that I tried the first one, then tried `make docker-simulator-tests`, which got further and started building things. I interrupted that because it takes too long, tried the second one, then tried it again without setting `TEST_PATH`, and now it fails.

**Comment by obra** [comment]
@gedankenexperimenter thanks so much for putting this through its paces.

> I tried running make docker-simulator-tests first, and got a confusing error message

Do you happen to remember what the weird error message was?

> I think it would be nice to have the makefile check for the existence of .arduino, and give the user a more helpful message, or perhaps event just go ahead and execute the setup target if it doesn't exist.

A better error message in the case of weird failures is definitely desirable. ".arduino not existing" isn't necessarily an error, especially if you have things checked out in a "classical" layout, which ought to have still worked. The Makefile should have detected your existing Arduino setup.

> make[4]: Entering directory '/kaleidoscope/testing/googletest/build'
/bin/sh: 1: cd: can't cd to /kaleidoscope/hardware/keyboardio/avr/libraries/Kaleidoscope/testing/googletest/build

I believe this error is due to you having a stale build inside Docker. Based on the lack of any kind of docker-related reports from the field on master, I suspect that you and I are the only folks regularly using Docker testing.  (ditto the TEST_PATH change)  If this process works for you, I suspect we're set:
```
$ make docker-bash
(it will open docker)
# make clean
# exit
$ make docker-simulator-test
```

If anyone else complains, I'm happy to put effort into an automated fix.

**Comment by gedankenexperimenter** [comment]
> Do you happen to remember what the weird error message was?
```
[merlin@sisyphus:~/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope] 2020-11-22 08:42
$ make docker-simulator-tests
Arduino user directory /Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user
ARDUINO_DIRECTORIES_USER="/Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user" ./bin/run-docker "make simulator-tests "
Preparing Kaleidoscope and the bundle...
The bundle is coming from /Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user/hardware/keyboardio
./bin/run-docker: line 37: cd: /Users/merlin/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope/.arduino/user/hardware/keyboardio: No such file or directory
make: *** [docker-simulator-tests] Error 1
```

**Comment by gedankenexperimenter** [comment]
> I believe this error is due to you having a stale build inside Docker. Based on the lack of any kind of docker-related reports from the field on master, I suspect that you and I are the only folks regularly using Docker testing. (ditto the TEST_PATH change) If this process works for you, I suspect we're set:

Running `make clean` inside Docker did clear whatever stale cache was preventing the tests from running completely. However, I still can't run just a subset of the tests; `make docker-simulator-tests TEST_PATH=tests/examples` doesn't work:
```
[merlin@sisyphus:~/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope] 2020-11-22 15:52
$ make docker-simulator-tests TEST_PATH=tests/examples
Arduino user directory /Users/merlin/Documents/Arduino/
ARDUINO_DIRECTORIES_USER="/Users/merlin/Documents/Arduino/" ./bin/run-docker "make simulator-tests "TEST_PATH='tests/examples'""
Preparing Kaleidoscope and the bundle...
The bundle is coming from /Users/merlin/Documents/Arduino//hardware/keyboardio
Building the docker image...
sha256:40524e9495190392192938613b90d8cc8ef24579f9c7132e213ee07f5f5ff4fc
Syncing Kaleidoscope...
Syncing the bundle...
Arduino user directory /kaleidoscope/.arduino/user/
/usr/bin/arduino-cli config init
Config file written to: /arduino-cli/data/arduino-cli.yaml
make -C tests all
make[1]: Entering directory '/kaleidoscope/tests'
find: 'tests/examples': No such file or directory
find: 'tests/examples': No such file or directory
find: 'tests/examples': No such file or directory
find: 'tests/examples': No such file or directory
```

**Comment by gedankenexperimenter** [comment]
Maybe it's looking for a directory name relative to `tests` now, but that also fails:
```
[merlin@sisyphus:~/src/Kaleidoscope-Bundle-Keyboardio/avr/libraries/Kaleidoscope] 2020-11-22 16:00
$ make docker-simulator-tests TEST_PATH=examples
Arduino user directory /Users/merlin/Documents/Arduino/
ARDUINO_DIRECTORIES_USER="/Users/merlin/Documents/Arduino/" ./bin/run-docker "make simulator-tests "TEST_PATH='examples'""
Preparing Kaleidoscope and the bundle...
The bundle is coming from /Users/merlin/Documents/Arduino//hardware/keyboardio
Building the docker image...
sha256:40524e9495190392192938613b90d8cc8ef24579f9c7132e213ee07f5f5ff4fc
Syncing Kaleidoscope...
Syncing the bundle...
Arduino user directory /kaleidoscope/.arduino/user/
/usr/bin/arduino-cli config init
Config file written to: /arduino-cli/data/arduino-cli.yaml
make -C tests all
make[1]: Entering directory '/kaleidoscope/tests'
cd /kaleidoscope/testing/googletest/build && make
make[2]: Entering directory '/kaleidoscope/testing/googletest/build'
make[3]: Entering directory '/kaleidoscope/testing/googletest/build'
make[4]: Entering directory '/kaleidoscope/testing/googletest/build'
make[4]: Leaving directory '/kaleidoscope/testing/googletest/build'
[ 25%] Built target gtest
make[4]: Entering directory '/kaleidoscope/testing/googletest/build'
make[4]: Leaving directory '/kaleidoscope/testing/googletest/build'
[ 50%] Built target gmock
make[4]: Entering directory '/kaleidoscope/testing/googletest/build'
make[4]: Leaving directory '/kaleidoscope/testing/googletest/build'
[ 75%] Built target gmock_main
make[4]: Entering directory '/kaleidoscope/testing/googletest/build'
make[4]: Leaving directory '/kaleidoscope/testing/googletest/build'
[100%] Built target gtest_main
make[3]: Leaving directory '/kaleidoscope/testing/googletest/build'
make[2]: Leaving directory '/kaleidoscope/testing/googletest/build'
make -f /kaleidoscope/testing/makefiles/testcase.mk -C examples/basic-keypress testcase=examples/basic-keypress build
make[2]: Entering directory '/kaleidoscope/tests/examples/basic-keypress'
Arduino user directory /kaleidoscope/.arduino/user/
Compiling examples/basic-keypress ktest script into test/generated-testcase.cpp
perl /kaleidoscope/testing/bin/ktest-to-cxx \
	--ktest=test.ktest \
	--cxx=test/generated-testcase.cpp
ccache  -o "/kaleidoscope/_build/examples/basic-keypress/obj/generated-testcase.o" -c -std=c++14 \
	-I/kaleidoscope -I/kaleidoscope/src -I/kaleidoscope/.arduino/user//hardware/keyboardio/virtual//cores/arduino -I/kaleidoscope/.arduino/user//hardware/keyboardio/virtual//libraries/KeyboardioHID/src -I/kaleidoscope/testing/googletest/googlemock/include -I/kaleidoscope/testing/googletest/googletest/include  -DARDUINO=10607 -DARDUINO_ARCH_VIRTUAL -DKALEIDOSCOPE_VIRTUAL_BUILD=1 -DKEYBOARDIOHID_BUILD_WITHOUT_HID=1 -DUSBCON=dummy -DARDUINO_ARCH_AVR=1 -DARDUINO_AVR_MODEL01 '-DKALEIDOSCOPE_HARDWARE_H="Kaleidoscope-Hardware-Model01.h"' '-DUSB_PRODUCT="Model 01"' test/generated-testcase.cpp
ccache: error: missing equal sign in "/kaleidoscope/_build/examples/basic-keypress/obj/generated-testcase.o"
make[2]: *** [/kaleidoscope/testing/makefiles/testcase.mk:83: /kaleidoscope/_build/examples/basic-keypress/obj/generated-testcase.o] Error 1
make[2]: Leaving directory '/kaleidoscope/tests/examples/basic-keypress'
make[1]: *** [Makefile:63: examples/basic-keypress] Error 2
make[1]: Leaving directory '/kaleidoscope/tests'
make: *** [Makefile:35: simulator-tests] Error 2
make: *** [docker-simulator-tests] Error 2
```

**Comment by gedankenexperimenter** [comment]
I could work around this by having my wrapper script delete everything under `tests/` that's not in the target path, then run `make docker-simulator-tests`, then restore those deleted files, but I'd really prefer it if I don't have to resort to that.

**Comment by obra** [comment]
It is indeed looking for a path relative to tests/ now. 

The old design made it much easier to shoot yourself in the foot, something I did constantly but when I did not prepend tests/ 

You shouldn’t need to work around this other than no longer including tests/ as a prefix. 

when I’m back at a computer, I’ll see if I can reproduce the error you were running into.  it looks some thing I hit early in development, but don’t remember what was supposed to fix it

**Comment by gedankenexperimenter** [comment]
> It is indeed looking for a path relative to tests/ now. The old design made it much easier to shoot yourself in the foot, something I did constantly but when I did not prepend tests/

Interesting. I use a wrapper script, so I can leverage command-line tab completion of the path name to avoid typos. It makes a lot more sense to me to specify the path relative to the current working directory, but it won't be a big deal to adjust it to strip `tests/` from the start of the path once it gets merged. Right now, it's a moot point until that feature works in the first place.

**Pull request merged**
